# Generated by Django 5.0.7 on 2024-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=10, null=True)),
                ('second_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
