# Generated by Django 5.0.7 on 2024-07-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullDitails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=100)),
                ('birth_year', models.DateField()),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'full_ditails',
            },
        ),
    ]
